generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CrashReport
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          crash_report
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        sort: [count, desc]
        object_actions:
          resolved:      ~
          _edit:         ~
          _delete:       ~
        display: [androirc_version, android_version, error_message, count, is_resolved]
        actions: []
      filter:
        display: [androirc_version, android_version, is_resolved]
      form:    ~
      edit:    ~
      new:     ~
