generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Donator
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          donator
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, _amount]
      filter:
        display: [name]
      form:    ~
      edit:    ~
      new:     ~
