<?php

/**
 * BaseTipHoliday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $language
 * @property date $date_start
 * @property date $date_end
 * @property clob $content
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getLanguage()   Returns the current record's "language" value
 * @method date       getDateStart()  Returns the current record's "date_start" value
 * @method date       getDateEnd()    Returns the current record's "date_end" value
 * @method clob       getContent()    Returns the current record's "content" value
 * @method TipHoliday setId()         Sets the current record's "id" value
 * @method TipHoliday setLanguage()   Sets the current record's "language" value
 * @method TipHoliday setDateStart()  Sets the current record's "date_start" value
 * @method TipHoliday setDateEnd()    Sets the current record's "date_end" value
 * @method TipHoliday setContent()    Sets the current record's "content" value
 * 
 * @package    androirc
 * @subpackage model
 * @author     MewT
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipHoliday extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('androirc_tip_holiday');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('language', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('date_start', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('date_end', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}