<?php

/**
 * BaseQuickStart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $language
 * @property string $verion_min
 * @property string $verion_max
 * @property clob $content
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getLanguage()   Returns the current record's "language" value
 * @method string     getVerionMin()  Returns the current record's "verion_min" value
 * @method string     getVerionMax()  Returns the current record's "verion_max" value
 * @method clob       getContent()    Returns the current record's "content" value
 * @method QuickStart setId()         Sets the current record's "id" value
 * @method QuickStart setLanguage()   Sets the current record's "language" value
 * @method QuickStart setVerionMin()  Sets the current record's "verion_min" value
 * @method QuickStart setVerionMax()  Sets the current record's "verion_max" value
 * @method QuickStart setContent()    Sets the current record's "content" value
 * 
 * @package    androirc
 * @subpackage model
 * @author     MewT
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuickStart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('androirc_quick_start');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('language', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('verion_min', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('verion_max', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}