<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }
    
    public function getLastArticles($limit = 10)
    {
        $query = $this->createQuery('a')
                    ->where('a.is_visible=1')
                    ->orderBy('id DESC')
                    ->limit($limit);
                    
        return $query->execute();
    }
}