<?php

/**
 * ChangeLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    androirc
 * @subpackage model
 * @author     MewT
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ChangeLog extends BaseChangeLog
{
}
