<?php

/**
 * DonatorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DonatorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DonatorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Donator');
    }
}