homepage:
  url:   /
  param: { module: article, action: index }

article_show:
  url: /article/:id/:slug
  class: sfDoctrineRoute
  options: { model: Article, type: object }
  param: { module: article, action: show }
  requirements:
    id: \d+
    sf_method: [get]
    
article_atom:
  url: /article/atom
  param: { module: article, action: index, sf_format: atom }
  
donate:
  url: /donate
  param: { module: donate, action: index }

eula:
  url: /eula
  param: { module: eula, action: index }

screenshots:
  url: /screenshots
  param: { module: screenshots, action: index }
    
contact:
  url: /contact
  param: { module: contact, action: index }

beta:
  url: /beta
  param: { module: beta, action: index }
  
beta_latest:
  url: /beta/latest
  param: { module: beta, action: latest }
  
beta_download:
  url: /beta/download
  param: { module: beta, action: download }
  
quickstart:
  url: /quickstart/:version/:lang
  param: { module: quickstart, action: index }
  options:
    segment_separators: [/]
    
tip:
  url: /tip/:lang/:date
  param: { module: tip, action: index }
  
tip_without_date:
  url: /tip/:lang
  param: { module: tip, action: index }
  
changelog:
  url: /changelog/:version
  param: { module: changelog, action: index }
  options:
    segment_separators: [/]
    
crashreport:
  url: /crashreport
  params: { module: crashreport, action: index }
  
format:
  url: /format
  params: { module: default, action: format }
  
image_thumbnail:
  url: /image/thumbnail/:image
  param: { module: image, action: thumbnail }
  options:
    segment_separators: [/]