generator:
  class: sfDoctrineGenerator
  param:
    model_class:           QuickStart
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quick_start
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        version_min:      { help: The minimum version (e.g. 2.3.1) }
        version_max:      { help: The maximum version (e.g. 2.3.1) }
      list:
        title: Quickstarts
        display: [language, version_min, version_max]
      filter:
        display: [language]
      form:    ~
      edit:    ~
      new:     ~
