generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BetaRelease
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          beta_release
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [version, _downloads, revision, is_downloadable]
      filter:
        display: [version]
      form:    ~
      edit:
        display: [version, revision, is_downloadable, file]
      new:     ~
