generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ChangeLog
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          change_log
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [version, created_at]
      filter:
        display: [version]
      form:    ~
      edit:    ~
      new:
        title: Add a new ChangeLog
