generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tip
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tip
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        display: [language, content]
      filter:
        display: [language]
      form:    ~
      edit:    ~
      new:     ~
