Article:
  tableName: androirc_article
  actAs: 
    Timestampable: ~
    Sluggable:
      fileds: [title]
      canUpdate: true
  columns:
    id:                       { type: integer, primary: true, autoincrement: true}
    sf_guard_user_id:         { type: integer }
    title:                    { type: string(255), notnull: true }
    content:                  { type: clob, notnull: true }
    is_visible:               { type: boolean, default: true }
  relations:
    sfGuardUser:
      onDelete: SET NULL
      onUpdate: CASCADE
      foreignAlias: Articles
            
BetaRelease:
  tableName: androirc_beta_release
  actAs:
    Timestampable: ~
  columns:
    id:                       { type: integer, primary: true, autoincrement: true}
    version:                  { type: string(100) }
    is_downloadable:          { type: boolean, default: true }
    path:                     { type: string(255) }
    
BetaDownload:
  tableName: androirc_beta_download
  actAs:
    Timestampable: ~
  columns:
    id:                       { type: integer, primary: true, autoincrement: true}
    beta_release_id:          { type: integer }
    location:                 { type: string(50) }
  relations:
    BetaRelease:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: Downloads
    
Tip:
  tableName: androirc_tip
  columns:
    id:                       { type: integer, primary: true, autoincrement: true }
    language:                 { type: string(2), notnull: true }
    content:                  { type: clob, notnull: true }
    
TipHoliday:
  tableName: androirc_tip_holiday
  columns:
    id:                       { type: integer, primary: true, autoincrement: true }
    language:                 { type: string(2), notnull: true }
    date_start:               { type: date, notnull: true }
    date_end:                 { type: date, notnull: true }
    content:                  { type: clob }
    
QuickStart:
  tableName: androirc_quick_start
  columns:
    id:                       { type: integer, primary: true, autoincrement: true }
    language:                 { type: string(2), notnull: true }
    verion_min:               { type: string(20), notnull: true }
    verion_max:               { type: string(20), notnull: true }
    content:                  { type: clob, notnull: true }
    
CrashReport:
  tableName: androirc_crash_report
  actAs:
    Timestampable: ~
  columns:
    id:                       { type: integer, primary: true, autoincrement: true }
    phone_model:              { type: string(200) }
    android_version:          { type: string(200) }
    thread_name:              { type: string(200) }
    error_message:            { type: clob }
    callstack:                { type: clob }
    androirc_version:         { type: string(200) }
  