Article:
  actAs: 
    Timestampable: ~
    Sluggable:
      fileds: [title]
      canUpdate: true
  columns:
    id:                       { type: integer, primary: true, autoincrement: true}
    sf_guard_user_id:         { type: integer }
    title:                    { type: string(255), notnull: true }
    content:                  { type: clob, notnull: true }
    is_visible:               { type: boolean, default: true }
  relations:
    sfGuardUser:
      onDelete: SET NULL
      onUpdate: CASCADE
      foreignAlias: Articles
            
Beta:
  actAs:
    Timestampable: ~
  columns:
    id:                       { type: integer, primary: true, autoincrement: true}
    version:                  { type: string(100) }
    is_downloadable:          { type: boolean, default: true }
    path:                     { type: string(255) }